/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab9p2_diegocruzjunniorsauceda;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dfcm9
 */
public class Main extends javax.swing.JFrame {

    ArrayList<Registro> registros = new ArrayList();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        JPB_progreso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tp_crud = new javax.swing.JTabbedPane();
        jp_Agregar = new javax.swing.JPanel();
        tf_orderid = new javax.swing.JTextField();
        tf_shipmode = new javax.swing.JTextField();
        tf_segment = new javax.swing.JTextField();
        tf_state = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_orderdate = new javax.swing.JTextField();
        tf_shipdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_customerid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_country = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_postalcode = new javax.swing.JTextField();
        tf_customername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_city = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_region = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_productID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_category = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_subcategory = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_productname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tf_sales = new javax.swing.JTextField();
        tf_quantity = new javax.swing.JTextField();
        tf_discount = new javax.swing.JTextField();
        tf_profit = new javax.swing.JTextField();
        jb_agregar = new javax.swing.JButton();
        jp_Listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listas = new javax.swing.JTextArea();
        jb_listorders = new javax.swing.JButton();
        jb_listdetails = new javax.swing.JButton();
        jb_listcustomers = new javax.swing.JButton();
        jb_listproducts = new javax.swing.JButton();
        jb_clearArea = new javax.swing.JButton();
        jp_Eliminar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_eliminar = new javax.swing.JTable();
        jb_eliminar = new javax.swing.JButton();
        jb_update = new javax.swing.JButton();
        JPB_progreso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tp_crud.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_crudStateChanged(evt);
            }
        });

        jp_Agregar.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Order ID:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ship Mode:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Segment:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("State:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Date:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer ID:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Country:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Postal Code:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Customer Name:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Product ID:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Region");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Category:");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sub-Category:");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ship Date:");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Product Name:");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Sales:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Quantity:");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Discount:");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Profit:");

        jb_agregar.setBackground(new java.awt.Color(102, 102, 102));
        jb_agregar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jb_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jb_agregar.setText("Agregar Registro");
        jb_agregar.setFocusable(false);
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_AgregarLayout = new javax.swing.GroupLayout(jp_Agregar);
        jp_Agregar.setLayout(jp_AgregarLayout);
        jp_AgregarLayout.setHorizontalGroup(
            jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_AgregarLayout.createSequentialGroup()
                        .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_state, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_segment, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_shipmode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_productID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_AgregarLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_category, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_AgregarLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_country, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jp_AgregarLayout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jp_AgregarLayout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tf_orderdate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(tf_city, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                                    .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jp_AgregarLayout.createSequentialGroup()
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jp_AgregarLayout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)))
                                    .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_shipdate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_customername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_region, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_AgregarLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_subcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(jp_AgregarLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sales, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_AgregarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_AgregarLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_profit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jp_AgregarLayout.setVerticalGroup(
            jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_orderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_orderdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_shipdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_shipmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_customername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_postalcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_productID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_subcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jp_AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_profit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jb_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        tp_crud.addTab("Agregar Registro", jp_Agregar);

        jp_Listar.setBackground(new java.awt.Color(204, 204, 204));

        ta_listas.setColumns(20);
        ta_listas.setRows(5);
        jScrollPane1.setViewportView(ta_listas);

        jb_listorders.setBackground(new java.awt.Color(0, 102, 0));
        jb_listorders.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jb_listorders.setForeground(new java.awt.Color(255, 255, 255));
        jb_listorders.setText("Orders");
        jb_listorders.setFocusable(false);
        jb_listorders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listordersMouseClicked(evt);
            }
        });

        jb_listdetails.setBackground(new java.awt.Color(255, 153, 0));
        jb_listdetails.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jb_listdetails.setForeground(new java.awt.Color(255, 255, 255));
        jb_listdetails.setText("Details");
        jb_listdetails.setFocusable(false);
        jb_listdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listdetailsMouseClicked(evt);
            }
        });

        jb_listcustomers.setBackground(new java.awt.Color(255, 51, 51));
        jb_listcustomers.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jb_listcustomers.setForeground(new java.awt.Color(255, 255, 255));
        jb_listcustomers.setText("Customers");
        jb_listcustomers.setFocusable(false);
        jb_listcustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listcustomersMouseClicked(evt);
            }
        });

        jb_listproducts.setBackground(new java.awt.Color(51, 51, 255));
        jb_listproducts.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jb_listproducts.setForeground(new java.awt.Color(255, 255, 255));
        jb_listproducts.setText("Products");
        jb_listproducts.setFocusable(false);
        jb_listproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_listproductsMouseClicked(evt);
            }
        });

        jb_clearArea.setBackground(new java.awt.Color(0, 204, 204));
        jb_clearArea.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jb_clearArea.setForeground(new java.awt.Color(255, 255, 255));
        jb_clearArea.setText("Clear");
        jb_clearArea.setFocusable(false);
        jb_clearArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clearAreaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_ListarLayout = new javax.swing.GroupLayout(jp_Listar);
        jp_Listar.setLayout(jp_ListarLayout);
        jp_ListarLayout.setHorizontalGroup(
            jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ListarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_ListarLayout.createSequentialGroup()
                        .addComponent(jb_listorders, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jb_listdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jb_listcustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jb_listproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_clearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jp_ListarLayout.setVerticalGroup(
            jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ListarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_listorders, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_listdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_listcustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_listproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_clearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tp_crud.addTab("Listar Registro", jp_Listar);

        jp_Eliminar.setBackground(new java.awt.Color(204, 204, 204));

        jt_eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Row ID", "Order ID", "Order Date", "Customer ID", "Country", "City", "Product ID", "Sales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_eliminar);

        jb_eliminar.setBackground(new java.awt.Color(102, 102, 102));
        jb_eliminar.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jb_eliminar.setText("Eliminar Registro");
        jb_eliminar.setFocusable(false);
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        jb_update.setBackground(new java.awt.Color(102, 102, 102));
        jb_update.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jb_update.setForeground(new java.awt.Color(255, 255, 255));
        jb_update.setText("Update Tabla");
        jb_update.setFocusable(false);
        jb_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_updateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_EliminarLayout = new javax.swing.GroupLayout(jp_Eliminar);
        jp_Eliminar.setLayout(jp_EliminarLayout);
        jp_EliminarLayout.setHorizontalGroup(
            jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_EliminarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_EliminarLayout.createSequentialGroup()
                        .addComponent(jb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jp_EliminarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        jp_EliminarLayout.setVerticalGroup(
            jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_EliminarLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        tp_crud.addTab("Eliminar Registro", jp_Eliminar);

        JPB_progreso.setBackground(new java.awt.Color(153, 153, 153));
        JPB_progreso.setForeground(new java.awt.Color(204, 204, 204));
        JPB_progreso.setOpaque(true);
        JPB_progreso.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tp_crud)
                    .addComponent(JPB_progreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPB_progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(tp_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        try {
            String OrderID = tf_orderid.getText();
            String OrderDate = tf_orderdate.getText();
            String ShipDate = tf_shipdate.getText();
            String ShipMode = tf_shipmode.getText();
            String CustomerID = tf_customerid.getText();
            String CustomerName = tf_customername.getText();
            String Segment = tf_segment.getText();
            String Country = tf_country.getText();
            String City = tf_city.getText();
            String State = tf_state.getText();
            String PostalCode = tf_postalcode.getText();
            String Region = tf_region.getText();
            String ProductID = tf_productID.getText();
            String Category = tf_category.getText();
            String SubCateg = tf_subcategory.getText();
            String ProductName = tf_productname.getText();
            String Sales = tf_sales.getText();
            String Quantity = tf_quantity.getText();
            String Discount = tf_discount.getText();
            String Profit = tf_profit.getText();

            Registro newre = new Registro(OrderID, OrderDate, ShipDate, ShipMode, CustomerID, CustomerName, Segment, Country, City, State, PostalCode, Region, ProductID,
                    Category, SubCateg, ProductName, Sales, Quantity, Discount, Profit);
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            try {

                db.query.execute("INSERT INTO TenRecordReal"
                        + " ([Order ID], [Order Date], [Ship Date],[Ship Mode], [Customer ID], [Customer Name], Segment, Country, City, State, [Postal Code], Region, [Product ID], Category, [Sub-Category], [Product Name], Sales, Quantity, Discount, Profit )"
                        + " VALUES ('" + OrderID + "', '" + OrderDate + "', '" + ShipDate + "', '" + ShipMode + "', '" + CustomerID + "', '" + CustomerName + "', '" + Segment + "', '" + Country + "', '" + City + "', '" + State + "', '" + PostalCode + "', '" + Region + "', '" + ProductID + "', '" + Category + "', '" + SubCateg + "', '" + ProductName + "', '" + Sales + "', '" + Quantity + "', '" + Discount + "', '" + Profit + "')");
                db.commit();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
            Thread H = new Hilo(Color.yellow, JPB_progreso, "Agregado Exitosamente", 17);
            JPB_progreso.setVisible(true);
            JPB_progreso.setForeground(Color.yellow);
            JPB_progreso.setBackground(Color.GRAY);
            H.start();
            
            tf_orderid.setText("");
            tf_orderdate.setText("");
            tf_shipdate.setText("");
            tf_shipmode.setText("");
            tf_customerid.setText("");
            tf_customername.setText("");
            tf_segment.setText("");
            tf_country.setText("");
            tf_city.setText("");
            tf_state.setText("");
            tf_postalcode.setText("");
            tf_region.setText("");
            tf_productID.setText("");
            tf_category.setText("");
            tf_subcategory.setText("");
            tf_productname.setText("");
            tf_sales.setText("");
            tf_quantity.setText("");
            tf_discount.setText("");
            tf_profit.setText("");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        try {
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            try {

                db.query.execute("delete from TenRecordReal where id = " + jt_eliminar.getValueAt(jt_eliminar.getSelectedRow(), 0));
                db.commit();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            db.desconectar();
            Thread H = new Hilo(new Color(160, 11, 246), JPB_progreso, "Eliminado Exitosamente", 20);
            JPB_progreso.setVisible(true);
            JPB_progreso.setForeground(new Color(160, 11, 246));
            JPB_progreso.setBackground(Color.GRAY);
            H.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error!");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void tp_crudStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_crudStateChanged
        
    }//GEN-LAST:event_tp_crudStateChanged

    private void jb_listordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listordersMouseClicked
        try {
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            db.query.execute("select [Order ID], [Order Date], [Ship Date], [Ship Mode], [Customer ID] from TenRecordReal");
            ResultSet rs = db.query.getResultSet();
            String shower = "";
            int cont = 1;
            while (rs.next()) {
                shower += "Order " + cont + "\n";
                shower += "Order ID: " + rs.getString(1) + "\n";
                shower += "Order Date: " + rs.getString(2) + "\n";
                shower += "Ship Date: " + rs.getString(3) + "\n";
                shower += "Ship Mode: " + rs.getString(4) + "\n";
                shower += "Customer ID: " + rs.getString(5) + "\n";
                shower += "\n";
                cont++;
            }
            Thread H = new Hilo(Color.green, JPB_progreso, ta_listas, "Orders Listados", shower, 25);
            JPB_progreso.setVisible(true);
            JPB_progreso.setForeground(Color.green);
            JPB_progreso.setBackground(Color.GRAY);
            H.start();

            db.desconectar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_listordersMouseClicked

    private void jb_listdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listdetailsMouseClicked
        try {
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            db.query.execute("select [Order ID], [Product ID], [Sales], [Quantity], [Discount], [Profit] from TenRecordReal");
            ResultSet rs = db.query.getResultSet();
            String shower = "";
            int cont = 1;
            while (rs.next()) {
                shower += "Details from Order " + cont + "\n";
                shower += "Order ID: " + rs.getString(1) + "\n";
                shower += "Product ID: " + rs.getString(2) + "\n";
                shower += "Sales: " + rs.getString(3) + "\n";
                shower += "Quantity: " + rs.getString(4) + "\n";
                shower += "Discount: " + rs.getString(5) + "\n";
                shower += "Profit: " + rs.getString(6) + "\n";
                shower += "\n";
                cont++;
            }

            Thread H = new Hilo(Color.orange, JPB_progreso, ta_listas, "Details Listados", shower, 20);
            JPB_progreso.setVisible(true);
            JPB_progreso.setForeground(Color.orange);
            JPB_progreso.setBackground(Color.GRAY);
            H.start();
            db.desconectar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_listdetailsMouseClicked

    private void jb_listcustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listcustomersMouseClicked
        try {
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            db.query.execute("select [Customer ID], [Customer Name], [Segment], [Country], [City], [State], [Postal Code], [Region] from TenRecordReal");
            ResultSet rs = db.query.getResultSet();
            String shower = "";
            int cont = 1;
            while (rs.next()) {
                shower += "Customer  " + cont + "\n";
                shower += "Customer ID: " + rs.getString(1) + "\n";
                shower += "Customer Name: " + rs.getString(2) + "\n";
                shower += "Segment: " + rs.getString(3) + "\n";
                shower += "Country: " + rs.getString(4) + "\n";
                shower += "City: " + rs.getString(5) + "\n";
                shower += "State: " + rs.getString(6) + "\n";
                shower += "Postal Code: " + rs.getString(7) + "\n";
                shower += "Region: " + rs.getString(8) + "\n";
                shower += "\n";
                cont++;
            }

            Thread H = new Hilo(Color.red, JPB_progreso, ta_listas, "Customers Listados", shower, 17);
            JPB_progreso.setVisible(true);
            JPB_progreso.setForeground(Color.red);
            JPB_progreso.setBackground(Color.GRAY);
            H.start();
            db.desconectar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_listcustomersMouseClicked

    private void jb_listproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_listproductsMouseClicked
        // TODO add your handling code here:
        try {
            Dba db = new Dba("./BaseDatosLab.accdb");
            db.conectar();
            db.query.execute("select [Product ID], [Category], [Sub-Category], [Product Name] from TenRecordReal");
            ResultSet rs = db.query.getResultSet();
            String shower = "";
            int cont = 1;
            while (rs.next()) {
                shower += "Product  " + cont + "\n";
                shower += "Product ID: " + rs.getString(1) + "\n";
                shower += "Category: " + rs.getString(2) + "\n";
                shower += "Sub-Category: " + rs.getString(3) + "\n";
                shower += "Product Name: " + rs.getString(4) + "\n";
                shower += "\n";
                cont++;
            }
            
            Thread H = new Hilo(Color.blue, JPB_progreso, ta_listas, "Products Listados", shower, 34);
            JPB_progreso.setForeground(Color.BLUE);
            JPB_progreso.setBackground(Color.GRAY);
            JPB_progreso.setVisible(true);
            H.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error.");
            e.printStackTrace();
        }

    }//GEN-LAST:event_jb_listproductsMouseClicked

    private void jb_clearAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clearAreaMouseClicked
        // TODO add your handling code here:
        try {
            Thread H = new Hilo(Color.blue, JPB_progreso, ta_listas, "Text Area Limpiado", "", 50);
            JPB_progreso.setForeground(Color.CYAN);
            JPB_progreso.setBackground(Color.GRAY);
            JPB_progreso.setVisible(true);
            H.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error.");
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_jb_clearAreaMouseClicked

    private void jb_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_updateMouseClicked
        try {
            
                DefaultTableModel modelo = (DefaultTableModel) jt_eliminar.getModel();
                modelo.setRowCount(0);
                registros.clear();
                
                Dba db = new Dba("./BaseDatosLab.accdb");
                db.conectar();
                try {
                    db.query.execute("select Id, [Order ID], [Order Date], [Customer ID], Country, City, [Product ID], Sales from TenRecordReal");
                    ResultSet rs = db.query.getResultSet();
                    while (rs.next()) {
                        registros.add(new Registro(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)));

                    }

                    for (Registro regs : registros) {
                        Object[] row = {regs.getLinea(), regs.getOrderId(), regs.getOrderDate(), regs.getCustomerId(), regs.getCountry(), regs.getCity(), regs.getProductId(), regs.getSales()};
                        
                        modelo.addRow(row);
                        
                    }
                    jt_eliminar.setModel(modelo);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                db.desconectar();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error!");
                e.printStackTrace();
            }
    }//GEN-LAST:event_jb_updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar JPB_progreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_clearArea;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_listcustomers;
    private javax.swing.JButton jb_listdetails;
    private javax.swing.JButton jb_listorders;
    private javax.swing.JButton jb_listproducts;
    private javax.swing.JButton jb_update;
    private javax.swing.JPanel jp_Agregar;
    private javax.swing.JPanel jp_Eliminar;
    private javax.swing.JPanel jp_Listar;
    private javax.swing.JTable jt_eliminar;
    private javax.swing.JTextArea ta_listas;
    private javax.swing.JTextField tf_category;
    private javax.swing.JTextField tf_city;
    private javax.swing.JTextField tf_country;
    private javax.swing.JTextField tf_customerid;
    private javax.swing.JTextField tf_customername;
    private javax.swing.JTextField tf_discount;
    private javax.swing.JTextField tf_orderdate;
    private javax.swing.JTextField tf_orderid;
    private javax.swing.JTextField tf_postalcode;
    private javax.swing.JTextField tf_productID;
    private javax.swing.JTextField tf_productname;
    private javax.swing.JTextField tf_profit;
    private javax.swing.JTextField tf_quantity;
    private javax.swing.JTextField tf_region;
    private javax.swing.JTextField tf_sales;
    private javax.swing.JTextField tf_segment;
    private javax.swing.JTextField tf_shipdate;
    private javax.swing.JTextField tf_shipmode;
    private javax.swing.JTextField tf_state;
    private javax.swing.JTextField tf_subcategory;
    private javax.swing.JTabbedPane tp_crud;
    // End of variables declaration//GEN-END:variables
}
